Linear Algebra

a) Matrices

In [17]:
import numpy as np
A = np.array([
    [2, -1],
    [0, 3],
    ])
B = np.array([
    [1, 2],
    [-3, 4],
    ])
# matrix addition A+B              
matrix_sum = A + B
print("a. A + B:")
print(matrix_sum)
print("\n")

# Matrix Multiplication
matrix_product = np.matmul(A,B)
print("b. AB:")
print(matrix_product)
print("\n")

# c. 3A - 2B
scalar_operation = 3*A - 2*B
print("c. 3A - 2B")
print(scalar_operation)

a. A + B:
[[ 3  1]
 [-3  7]]


b. AB:
[[ 5  0]
 [-9 12]]


c. 3A - 2B
[[ 4 -7]
 [ 6  1]]


b) Determinants and Inverses

In [18]:
import numpy as np

# Define matrix A
A = np.array([[2, -1],
              [0, 3]])

# Calculate determinant
det_A = np.linalg.det(A)
print("Determinant of A:")
print(det_A)
print("\n")

# Check if matrix is invertible (det ≠ 0)
print("Is A invertible?")
print(f"Yes, because det(A) = {det_A} ≠ 0")
print("\n")

# Calculate inverse if matrix is invertible
if det_A != 0:
    A_inv = np.linalg.inv(A)
    print("A inverse:")
    print(A_inv)
    
    # Verify the inverse by multiplying A * A^(-1)
    print("\nVerification (A * A^(-1) should give Identity matrix):")
    print(np.round(np.matmul(A, A_inv), decimals=10))

Determinant of A:
6.0


Is A invertible?
Yes, because det(A) = 6.0 ≠ 0


A inverse:
[[0.5        0.16666667]
 [0.         0.33333333]]

Verification (A * A^(-1) should give Identity matrix):
[[1. 0.]
 [0. 1.]]


c) Eigen Values and Eigenvectors

In [19]:
import numpy as np

# Define matrix C
C = np.array([[4, 1],
              [-2, 1]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(C)

# Print eigenvalues
print("Eigenvalues:")
print(eigenvalues)
print("\n")

# Print eigenvectors
print("Eigenvectors (as columns):")
print(eigenvectors)
print("\n")

# Verify the eigenvalue equation Cv = λv for each eigenpair
print("Verification of Cv = λv for each eigenpair:")
for i in range(len(eigenvalues)):
    print(f"\nEigenpair {i+1}:")
    print(f"λ = {eigenvalues[i]:.2f}")
    print(f"v = {eigenvectors[:, i]}")
    
    # Calculate Cv
    Cv = np.dot(C, eigenvectors[:, i])
    # Calculate λv
    lambda_v = eigenvalues[i] * eigenvectors[:, i]
    
    print("\nCv:")
    print(Cv)
    print("λv:")
    print(lambda_v)
    print("Cv ≈ λv:", np.allclose(Cv,lambda_v))

Eigenvalues:
[3. 2.]


Eigenvectors (as columns):
[[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


Verification of Cv = λv for each eigenpair:

Eigenpair 1:
λ = 3.00
v = [ 0.70710678 -0.70710678]

Cv:
[ 2.12132034 -2.12132034]
λv:
[ 2.12132034 -2.12132034]
Cv ≈ λv: True

Eigenpair 2:
λ = 2.00
v = [-0.4472136   0.89442719]

Cv:
[-0.89442719  1.78885438]
λv:
[-0.89442719  1.78885438]
Cv ≈ λv: True


4. 
You are given a dataset of cars with the following features:

Number of cylinders (x1​)

Engine size in liters (x2​)

Horsepower (x3)
car 1:
x1: 4
x2:  1.5
x3: 100
and price: 20

car 2:
x1: 6
x2:  2.0
x3: 150
and price: 30

Then, find the price of a car 3 with features
x1: 8
x2:  3.0
x3: 200
price:?

Hints:
1. Represent the given dataset as a matrix equation X.T*β=y, where X is the feature matrix, β is the coefficient vector, and y is the price vector  
2. Compute β (the coefficients) using the normal equation:
β=(X.T * X)^−1  X.T y

where,
X.T --> transpose matrix

In [21]:
import numpy as np

# Step 1: Create the feature matrix X (without intercept term to reduce parameters)
X = np.array([
    [4, 1.5, 100],  # First car
    [6, 2.0, 150]   # Second car
])

# Create the price vector y
y = np.array([20, 30])

# Add small regularization term to make matrix invertible
lambda_reg = 1e-5

# Calculate β using ridge regression formula: β = (X.T * X + λI)^(-1) * X.T * y
X_transpose = X.transpose()
X_transpose_X = np.dot(X_transpose, X)
identity_matrix = np.eye(X_transpose_X.shape[0])
regularized_matrix = X_transpose_X + lambda_reg * identity_matrix
X_transpose_X_inv = np.linalg.inv(regularized_matrix)
X_transpose_y = np.dot(X_transpose, y)
beta = np.dot(X_transpose_X_inv, X_transpose_y)

print("Coefficient vector β:")
print(beta)
print("\n")

# Create feature vector for the new car (without intercept)
X_new = np.array([8, 3.0, 200])

# Predict the price for the new car
predicted_price = np.dot(X_new, beta)

print("Predicted price for car 3:")
print(f"{predicted_price:.2f}")

# Show the equation
print("\nLinear equation:")
print(f"Price = {beta[0]:.2f}x₁ + {beta[1]:.2f}x₂ + {beta[2]:.2f}x₃")

Coefficient vector β:
[7.98722094e-03 1.43695216e-06 1.99680491e-01]


Predicted price for car 3:
40.00

Linear equation:
Price = 0.01x₁ + 0.00x₂ + 0.20x₃
